version: '3.1'

services:
    db:
        container_name: application_db
        image: mariadb:10.6.7
        # image: mysql:8.0.25
        platform: linux/arm64/v8
        # platform: linux/amd64
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - ./docker/mysql:/var/lib/mysql:Z
        environment:
            MYSQL_ROOT_PASSWORD: job_sharing
            MYSQL_DATABASE: job_sharing
        ports:
            - "3308:3306"
        networks:
            - application-network
    application: #php-fpm7.4
        build:
            context: .
            dockerfile: Dockerfile
        container_name: application
        restart: always
        privileged: true
        volumes:
            - ./:/var/www/php:Z
        working_dir: /var/www/php
        env_file:
            - .env
        networks:
            - application-network

    nginx: # Nginx service
        image: nginx:alpine
        container_name: nginx_container
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/php
            - ./docker/config/nginx/:/etc/nginx/conf.d/
        networks:
            - application-network
networks:
    application-network:
        driver: bridge
